export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const FEATURED_PROPERTIES_SUCCESS = "FEATURED_PROPERTIES_SUCCESS";
export const FEATURED_PROPERTIES_FAIL = "FEATURED_PROPERTIES_FAIL";



export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";